# vim: ft=zsh

# Ensure path arrays do not contain duplicates
typeset -gU cdpath fpath mailpath path;

#Determine what OS is running in
if [ "$(uname)" = "Darwin" ]; then
  OS='mac'
elif [ "$(expr substr $(uname -s) 1 5)" = "Linux" ]; then
  OS='linux'
elif [ "$(expr substr $(uname -s) 1 10)" = "MINGW32_NT" ]; then
  OS='cygwin'
fi

if [ "$(which gpg2)" != "gpg2 not found" ]; then
  export GPG=gpg2
fi

if [ "$OS" = "mac" ]; then
  # set PATH so it includes /usr/local before the regular
  # this will help in MacOS X to use brew's installed version isntead of the
  # outdated on MacOS
  path=(
    $(brew --prefix coreutils)/libexec/gnubin
    $(brew --prefix gnu-sed)/libexec/gnubin
    $(brew --prefix git)/share/git-core/contrib/diff-highlight
    /usr/local/{bin/sbin}
    $path
  )

  if [ -d /usr/local/opt/icu4c/bin ]; then
    path=(
      /usr/local/opt/icu4c/bin
      /usr/local/opt/icu4c/sbin
      $path
    )
  fi

  if [ -d /usr/local/sbin ]; then
    path=(
      /usr/local/sbin
      $path
    )
  fi

  if [ -d /usr/texbin ]; then
    path=(
      /usr/texbin
      $path
    )
  fi
fi

if [ "$OS" = "linux" ]; then
  path=(
    /usr/local/{bin/sbin}
    $path
  )

  if [ -f /usr/share/doc/git/contrib/diff-highlight/diff-highlight ]; then
    path=(
      /usr/share/doc/git/contrib/diff-highlight
      $path
    )
  fi
fi

# Set the basic list for the path
path=(
  /usr/local/{bin/sbin}
  $path
);

# If there's ~/bin then add it to the path
if [[ -d $HOME/bin ]]; then
  path=(
    $HOME/bin
    $path
  );
fi

# If there's the Heroku Toolbelt installed then load it to the path
if [[ -d /usr/local/heroku/bin ]]; then
  path=(
    /usr/local/heroku/bin
    $path
  );
fi

# If there's a ~/gocode folder, then there's where $GOPATH should point to.
if [[ -d $HOME/gocode ]]; then
  export GOPATH="$HOME/gocode";
  path=(
    ~/gocode/bin
    $path
  );
fi

if [[ -d $HOME/code/src ]]; then
  export GOPATH="$HOME/code";
  path=(
    ~/code/bin
    $path
  );
fi

# If there's $NAVEPATH then load it to the $PATH
if [[ -n $NAVEPATH ]]; then
  path=(
    $NAVEPATH
    $path
  );
fi

# If it's a mac then run ulimit -n 8192 because it sucks the little amount
# of concurrent files that can be open
if [[ "$OSTYPE" == darwin* ]]; then
  ulimit -n 8192;
fi

# Temporary files

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$USER";
  mkdir -p -m 700 "$TMPDIR";
fi

if [[ -d "$HOME/.nvm" ]]; then
  . ~/.nvm/nvm.sh
fi

TMPPREFIX="${TMPDIR%/}/zsh";
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX";
fi
